### ISSUE TITLE
Rename the repo?

### ISSUE THREAD

**Issue by awm33** [cognoma/core-service#10]
We started referring to this as the "core" or "core api". There was also the "brain" but I think that would be confusing in a ML project :).

Some ideas:
- cognoma/core
- cognoma/core-backend
- cognoma/core-api
- cognoma/core-service
- cognoma/api

Maybe others can post some suggestions?

**Comment by awm33** [comment]
@cgreene @gwaygenomics Any thoughts on this? If we rename (I really think we should) it's probably better to do it sooner

**Comment by cgreene** [comment]
I am not opposed, and I defer to @awm33 and @aelkner. I do agree that if we do it - before there are a lot of clones is the right time. @aelkner - thoughts on core-api?

**Comment by aelkner** [comment]
@awm33 @cgreene @gwaygenomics I think any server that receives HTTP requests can have an api, so I don't see the benefit of naming a package after that fact.  Really what we need is a good diagram like we've already developed to describe what each piece does.  I look at names like 'core-api' and 'api' and am left feeling that I know less, not more.  Let's keep updating the diagram as we understand more of what we are doing so that our system docs match what we eventually implement.  I doubt the names of the packages will need to change much.  Things the diagram could show:

1) django-cognoma - server of single-page app with rest api to serve said app
2) frontend - single-page app that calls into django-cognoma api
3) task-service - manger of tasks with rest api to serve django-cognoma
4) machine-learning - workers managed by task-service
5) cancer-data - the data used by machine-learning with abstractions where needed

I don't have a problem with tweaking any of these names, but I wouldn't spend too much time on it.  What was the term Andrew used, bike-shedding?

**Comment by dcgoss** [comment]
The argument for the distinction is based on the plan that there will be another django service for the task service. It may be helpful to think about what the name for that django repository would be? Ex: django-task-service, etc. This may help focus our thinking for the naming of this repo.

**Comment by awm33** [comment]
I think the name as is, makes it seem like it's a django congnoma package or library. The convention of {tech}-{name}-{another part of the name} is usually for libraries, like django-rest-framework, node-uuid (nodejs uuid package), clj-http (clojure http library).

I agree with @aelkner in that maybe we need to know more about what this repository's service will do.

To me, it's the "core" data models, or the application specific data models. So maybe app-service might be better, or even cognoma-service since it contains the application specific API paths. Maybe we should wait to see how we end up using it more. Unless a repository is designed to be reused like a package/library within other application, I like to name repositories by what they do. The ..-service postfix is common pattern used to indicate it's a process which runs independently and serves requests, typically HTTP.

**Comment by cgreene** [comment]
The word service keeps coming up. Is cognoma-service confusing with task-service, or does it provide more clarity by using them together?

**Comment by dcgoss** [comment]
My issue with cognoma-service is thatI don't think it is descriptive enough. Maybe something like core-django and task-service-django would be more clear.

**Comment by cgreene** [comment]
@awm33 @dcgoss @aelkner : renaming to "core-service" to accommodate all of the items raised above. @dcgoss : will mention that it's written in django to make it sufficiently descriptive.
