### ISSUE TITLE
Front end screen data needs

### ISSUE THREAD

**Issue by BobMiller** [cognoma/core-service#13]
Here is a list of Front End Screens and there associated data needs.

Login Screen
1) User Id
2) Password

    Note: User needs to be able to login anonymously.

Sample Chooser/ Status Chooser Screen

initial data input
1) List of tissues
1a) Tissue description (maybe?)
1b Tissue graphic (maybe?)
2) List of genes
2a)Gene decription (maybe?)

Algorithm Chooser Screen
initial data input
1) List of algorithms
1a) Algorithm descrition (maybe?)
2) Logic info about algorithms (TBD)

Job Submit screen
will send you all chosen data for job
1)selected tissues
2)selected genes
3)selected algorithm
4)user id

expect to receive back job status info for submitted job(s)

Question

while user is going from screen to screen selecting data, should we hold all data selection in browser session and send it to you when job request is submitted,

or 

send you the results of each screen and use the data you have to populate the job Submit screen?

**Comment by BobMiller** [comment]
Need also to add a Results Screen. Data  that gets returned will depend on algorithm they selected.

**Comment by ramjac** [comment]
We're thinking the basic form of the posted json for the Querying endpoint will be as follows:
{
   SampleID: <#ID corresponding to a tissue>,
   StatusText: <some text for the status data>,
   StatusType: <text, importFile, neo4j>,
   AlgorithmID: <#ID corresponding to a tissue>
}

We expect back something like this
HTTP status code indicating success, failure, errors..
{
   errors: [], //up to you but some list friendly of errors to report to the front end
   dataID: <the id of the results so that the front end can query for status>,
}

And then there will be some other Results endpoint which will be something like
HTTP GET yoururl.com/results/<dataID>

The response we can talk about later since we don't know what it will contain.

**Comment by BobMiller** [comment]
Grady,

I noticed in 

{
   SampleID: <#ID corresponding to a tissue>,
   StatusText: <some text for the status data>,
   StatusType: <text, importFile, neo4j>,
   AlgorithmID: <#ID corresponding to a tissue>
}

that the comment on AlgorithmID id is <#ID corresponding to a tissue> is this a typo? Should it read

AlgorithmID: <#ID corresponding to an algorithm>  ?

Also we may need to add another field: AlgorithmParameters, since some machine learning algorithms use input parameters. (Naturally we will provide on the algorithm chooser screen the default parameter settings for each algorithm type, but the user may wish to change them. So the Query endpoint data might look like

{
   SampleID: <#ID corresponding to a tissue>,
   StatusText: <some text for the status data>,
   StatusType: <text, importFile, neo4j>,
   AlgorithmID: <#ID corresponding to an algorithm>,
   AlgorithmParameters: <text listing algorithm parameters>
}

What do you think?

**Comment by ramjac** [comment]
That is a typo.

I some info can be provided in the StatusText. What parameters did you have
in mind? This could be something we missed.

JGF

**Comment by BobMiller** [comment]
Parameters would be different depending on what machine learning algorithm is chosen. Many of these algorithms do not have any parameters, but there are some that do. We will  not know until the machine learning group does their analysis. I included it just to let everyone know it is a possibility.

**Comment by awm33** [comment]
I think we've moved on to more detailed discussion in the frontend repos and API docs.
