### ISSUE TITLE
Determine branching pattern.

### ISSUE THREAD

**Issue by cgreene** [cognoma/core-service#26]
We should develop a common branching pattern with the front end so that someone working on one repo will be familiar with the patterns on the other.

**Comment by dhimmel** [comment]
I think @bdolly has a branching method. See https://github.com/cognoma/frontend/pull/16 which will be merged soon.

**Comment by awm33** [comment]
I would advise against using `master` as the production branch. Eventually something bad happens, someone merges into master when they shouldn't. Using a `production` branch has worked out better for projects I've been involved in. You also do not want to auto merge from a PR into whatever branch is used for continuous production deployment. So if master is used as prod, it should not be the default branch on GitHub, which essentially makes not the "master" branch, which is why I think making it explicit is less accident prone and self explanatory. We could do staging continuous deployment on master.

**Comment by awm33** [comment]
Me and @bdolly agreed on using a `production` branch
