### ISSUE TITLE
Continuous deployment to automatically deploy updates

### ISSUE THREAD

**Issue by dhimmel** [cognoma/core-service#52]
Let's look into how we can get CircleCI to deploy the codebase whenever `master` is updated.

**Comment by dhimmel** [comment]
I recently worked added continuous deployment using Travis CI to https://github.com/greenelab/deep-review, so happy to provide any help I can.

**Comment by awm33** [comment]
@amann Wanna help :)

**Comment by dcgoss** [comment]
Do we want to use CircleCI or Travis?

**Comment by dhimmel** [comment]
Let's start out using CircleCI since the repo is already configured with Circle.

If for some reason, AWS deployment from Circle proves difficult, we could try Travis. Tagging @kurtwheeler since he recently looked into continuous AWS deployment from CI.

**Comment by dcgoss** [comment]
In order for this to work we need to have an AWS ECR endpoint to push the containers to. This may already be in place. However, I don't have access to the account in order to view this information. @kurtwheeler can you see if this exists?

**Comment by dcgoss** [comment]
Also looks like https://github.com/silinternational/ecs-deploy will be a useful script for running the deployment from Circle

**Comment by bdolly** [comment]
@dhimmel would be nice to bake this into the front-end repo as well since it's tested with Circle CI

**Comment by kurtwheeler** [comment]
I did look into a continuous deployment pipeline with ECS and circleci last
week, I think I may have even come across that same script. There is an ECR
endpoint, it's listed in the the README here:
https://github.com/cognoma/core-service#logging-into-ecr. You won't be able
to use it without credentials though. You'll have figure something out with
@cgreene for that. I think I may have even had additional notes on that
continuous deployment, but they're on my work computer :(

**Comment by dcgoss** [comment]
To the best of my knowledge, a credential is needed in order to properly setup any CI pipeline. The server running the tests needs to have the credential in order to log in to ECR in order to push the built container and deploy the changes. Postponing my work on this issue until @kurtwheeler @cgreene / someone can provide me with a credential to use.

**Comment by kurtwheeler** [comment]
That's definitely correct. I cannot provide you with credentials though,
that's going to have to be @cgreene.

**Comment by dcgoss** [comment]
After several iterations and pull requests from the circleci branch, commit 83069d81d1c023ab30da0bb312eba4c4a232b58a has continuous deployment working from CircleCI. 

So, why did the build fail? The error message given from the deploy script is: `New task definition not running within 90 seconds`. This is something I had encountered earlier - when you tell our ECS cluster to update the cognoma-core-service, the new containers with the updated image are not being scheduled onto instances. So CircleCI is essentially pushing new task definitions, but those are perpetually "pending" deployment because the new containers never schedule. Something is wrong with the instances, and I don't think I have the AWS permissions to really make any changes. 

I SSHed into the two instances and checked things out. On 52.90.242.146 a simple `docker ps` results in a perpetual hang. Its logs haven't updated since April. On 54.227.183.159 docker is working and the logs are there, but inside the logs gives these errors:
![screen shot 2017-06-22 at 11 35 50 am](https://user-images.githubusercontent.com/7605010/27442801-39b1d894-573f-11e7-84c1-df0c44682733.png). 

I've done about as much as I can with the permissions I have, so pinging @kurtwheeler for this one.

**Comment by dcgoss** [comment]
Here is the errors given when inspecting the service via `aws ecs describe-services` for the core service. You can see how is a `desiredCount` of 2 but a `runningCount` of 0. Yes, this means api.cognoma.org is currently down.
![screen shot 2017-06-22 at 11 40 15 am](https://user-images.githubusercontent.com/7605010/27442978-c16b07b0-573f-11e7-9609-df513a6b1d34.png)
![screen shot 2017-06-22 at 11 40 26 am](https://user-images.githubusercontent.com/7605010/27442979-c173dd86-573f-11e7-9089-70ac9a227da1.png)

**Comment by dcgoss** [comment]
Because continuous deployment on CircleCI was implemented and this is more of a cognoma/infrastructure issue, I'm closing this issue and opening https://github.com/cognoma/infrastructure/issues/3.
